"""Add User and AccessToken tables

Revision ID: bfc729fb7141
Revises: ffa127977c1e
Create Date: 2024-12-16 17:35:13.336893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfc729fb7141'
down_revision: Union[str, None] = 'ffa127977c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('usermodel', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('usermodel', 'id')
    op.drop_column('usermodel', 'sensitive_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('sensitive_info', sa.VARCHAR(), nullable=False))
    op.add_column('usermodel', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('usermodel', 'hashed_password')
    op.drop_column('usermodel', 'username')
    # ### end Alembic commands ###
